### ISSUE TITLE
Suggestions for datepicker

### ISSUE THREAD

**Issue by coffeymatt** [valor-software/ng2-bootstrap#4431]
It would be great if the datepicker had a couple more capabilities:

- [ ] Option to prevent user typing their own input, i.e. force them to use the picker

- [ ] If you do allow typed input, mask it so it has to follow the format

- [ ] Include a clear button or x that removes the value

**Comment by robinbihun** [comment]
I would like to see the second one be an option, definitely. The other two, i see as nice to have - usually i have users request to type, but not a request to not be able to type a date.

**Comment by raydawg2000** [comment]
> Option to prevent user typing their own input, i.e. force them to use the picker

I just set the input field to readonly and that works well for me

**Comment by ankurraiyani** [comment]
I would like to see the second one be an option, as soon as possible.

**Comment by rkulinski** [comment]
Yes. Second option is great. But IMO manual input should update calendar. Now we can have situation where value inside input is different than the one currently selected in datepicker -  which seems kind of 'buggy' behaviour.

**Comment by ankurraiyani** [comment]
Yes we really need the second option as soon as possible. Also it should only allow digits.

**Comment by reddevilzee** [comment]
+1 for clear button

**Comment by N1RESH14** [comment]
is it possible to display date picker click on the calendar icon only? (I want input field and not display date picker focus on this input).
